In [44]:
import numpy as np

# ornegimizdeki fitness fonksiyon (minimize edilmesi gereken fonksiyon)
def objective_function(x):
    return x ** 2

def jaya_algorithm(pop_size, iter, bounds):
    # rassal olarak baslangic populasyonunu olustur
    population = np.random.uniform(bounds[0], bounds[1], pop_size)
    best_solution = None
    best_objective_value = float('inf')
    
    for iter in range(iter):
        # mevcut populasyondaki en iyi cozumu bul
        for individual in population:
            current_objective_value = objective_function(individual)

            if current_objective_value < best_objective_value: 
                best_objective_value = current_objective_value
                best_solution = individual
        
        # yeni populasyonu olustur
        new_population = []
    
        for individual in population:
            if np.random.rand() < 0.5:
                # iyi cozumlerden birine gore guncelle
                new_individual = individual + (best_solution - individual) * np.random.rand()
            else:
                # kotu cozumlerden birine gore guncelle
                worst_solution = max(population, key=objective_function)
                new_individual = individual - (worst_solution - individual) * np.random.rand()
            
            # yeni bireyi sinirlanidir
            new_individual = np.clip(new_individual, bounds[0], bounds[1])
            new_population.append(new_individual)
        
        population = np.array(new_population)
        print(f"ITER[{iter + 1}]:\n\n{population}\n")
        print(f"En iyi çözüm: {best_solution}, Hedef değeri: {best_objective_value}\n\n")
        print(f"--------------------------------------------------------------------\n")
    
    return best_solution, best_objective_value

# Parametreler
population_size = 3  # populasyon sayisi
iter = 100           # iterasyon sayisi
bounds = (-10, 10)   # alt ve ust sinir


best_sol, best_val = jaya_algorithm(population_size, iter, bounds)

print(f"en iyi cozum: {best_sol}, en iyi deger: {best_val}")


ITER[1]:

[-8.05074091  6.846887   -0.6579981 ]

En iyi çözüm: 3.3700256966368656, Hedef değeri: 11.357073195992792


--------------------------------------------------------------------

ITER[2]:

[-8.05074091  5.70143278 -0.6579981 ]

En iyi çözüm: -0.6579981025522845, Hedef değeri: 0.43296150296240676


--------------------------------------------------------------------

ITER[3]:

[-2.50645231  0.10726734 -0.02623087]

En iyi çözüm: -0.6579981025522845, Hedef değeri: 0.43296150296240676


--------------------------------------------------------------------

ITER[4]:

[-2.50645231  2.58641963  0.28379739]

En iyi çözüm: -0.026230866787058216, Hedef değeri: 0.0006880583724003938


--------------------------------------------------------------------

ITER[5]:

[-0.57936579  2.58641963  0.24813469]

En iyi çözüm: -0.026230866787058216, Hedef değeri: 0.0006880583724003938


--------------------------------------------------------------------

ITER[6]:

[-3.21426657  2.58641963 -0.584508